[build]
builder = "nixpacks"

[deploy]
startCommand = "cd apps/backend && pnpm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "8000" }

[[services]]
name = "geoscope-backend"
source = "." 